### ISSUE TITLE
Memorytyp 2 Bilder: Kann nur ein Bild verlinkt werden

### ISSUE THREAD

**Issue by Backdraft007** [geraldloss/glpairs#1]
Sobald man ein Bild verlinkt hat und speichert, wird dieses auch bei Bild 2 angezeigt.
Wenn man von vornherein 2 Bilder verlinkt, werden auf Bild 1 und Bild 2 zwei Bilder angezeigt.

Typo3: 10.4.12 Frisch installiert
glpairs: 2.2.4

**Comment by geraldloss** [comment]
Sorry für die späte Antwort, aber ist jetzt mit den aktutellen Updates behoben.
